# Generated by Django 5.1.7 on 2025-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_channels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_message_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
