# Generated by Django 5.1.7 on 2025-04-30 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_channels', '0003_channel_last_message_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Бан в канале',
                'verbose_name_plural': 'Баны в каналах',
            },
        ),
        migrations.RemoveConstraint(
            model_name='channelmembership',
            name='user_channel_unique_together',
        ),
        migrations.RemoveField(
            model_name='channelmembership',
            name='is_baned',
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_channel_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='channelmembership',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='membership_user_channel_unique_together'),
        ),
        migrations.AddField(
            model_name='channelban',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelban',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_info', to='text_channels.channel'),
        ),
        migrations.AddField(
            model_name='channelban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channelban',
            index=models.Index(fields=['user', 'channel'], name='text_channe_user_id_0e8eda_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelban',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='ban_user_channel_unique_together'),
        ),
    ]
