# Generated by Django 5.1.7 on 2025-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_remove_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connected_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='1951a76b', max_length=8, unique=True),
        ),
    ]
