# Generated by Django 5.1.7 on 2025-04-12 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_room_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.channel'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a273a798-6f00-4b9e-a970-78406c611c3c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'channel'], name='chat_channe_user_id_a14648_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token', 'channel'], name='chat_invita_token_2dda1f_idx'),
        ),
    ]
