# Generated by Django 5.1.7 on 2025-04-12 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_channelmembership_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('f6f2c92b-903e-43a1-84a4-acea53c445d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
