# Generated by Django 5.1.7 on 2025-04-12 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_uuid_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('994edc24-79dc-4d45-ade0-0effc950978c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
