# Generated by Django 5.1.7 on 2025-04-12 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expiration_period',
            field=models.CharField(choices=[('1', '1 час'), ('3', '3 часа'), ('24', '24 часа')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_in',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('dd76a98f-fe4b-4d77-b9f9-91341adda270'), editable=False, primary_key=True, serialize=False),
        ),
    ]
