# Generated by Django 5.1.7 on 2025-04-12 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_invitation_expiration_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('4b623b8d-7632-47ac-9ff2-69dd994aa274'), editable=False, primary_key=True, serialize=False),
        ),
    ]
