# Generated by Django 5.1.7 on 2025-04-12 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('bd25cbe3-101f-44d1-abcb-20b9f7757cd5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
