# Generated by Django 5.1.7 on 2025-04-12 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('0fa55d0e-5bd1-4d11-9536-3f769d1dc0d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
