# Generated by Django 5.1.7 on 2025-04-12 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('fdab9a3b-f280-43df-bcaf-72f572805758'), editable=False, primary_key=True, serialize=False),
        ),
    ]
