# Generated by Django 5.1.7 on 2025-04-12 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.UUID('89557b73-6c8b-4b36-ae18-d627dfb5d4ac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
