# Generated by Django 5.1.7 on 2025-04-18 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_channels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_in', models.DateTimeField(editable=False)),
                ('expiration_period', models.CharField(choices=[('1', '1 час'), ('3', '3 часа'), ('24', '24 часа')], default='1', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='text_channels.channel')),
            ],
            options={
                'verbose_name': 'Пригланешие',
                'verbose_name_plural': 'Приглашения',
                'indexes': [models.Index(fields=['uuid', 'channel'], name='invitations_uuid_16f639_idx')],
            },
        ),
    ]
