# Generated by Django 5.1.7 on 2025-04-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
