# Generated by Django 5.1.7 on 2025-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_messages', '0002_remove_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
