# Generated by Django 5.1.7 on 2025-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_channels', '0003_channel_last_message_number'),
        ('text_messages', '0003_message_is_deleted_message_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-number',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('channel', 'number')},
        ),
    ]
